### PR TITLE
Add zoom phone api

### PR DESCRIPTION
**Pull request by arska**
Hello @prschmid 

I added support for the zoom phone api (https://marketplace.zoom.us/docs/api-reference/zoom-api/phone/) with tests.

Thanks,
Aarno

### CODE REVIEW

**Comment by prschmid** [comment]
Hi @arska . Thank you for putting together a PR for this functionality! Could I trouble you to make this PR against the develop branch as per the [contribution guidelines](https://github.com/prschmid/zoomus/blob/master/CONTRIBUTING.md)? Thank you!

Once you do that and the tests pass, I'll be sure to review the PR. Looking forward to it!

**Comment by arska** [comment]
rebased on develop and tests pass. Maybe set "develop" as the default branch for this repo?

**Comment by prschmid** [comment]
@arska Thanks! I'll take a look at this later today/this weekend. I've also updated the default branch to develop to make things easier for everyone. Thanks for the suggestion!

**Comment by arska** [comment]
Hello @prschmid, migrated tests to responses and still all green!

**Pull request merged**
