### PR TITLE
Test using responses

### LINKED ISSUE #12: Proposal: Change tests to use the responses library
In working on #11, I'm becoming increasingly concerned that the current testing pattern is not going to be sufficient. It involves mocking helper methods and checking what they are called with. Then I saw this comment, on `components.base.BaseComponent`, in the `post_request` method.

>         Since the Zoom.us API only uses POST requests and each post request
>        must include all of the config data, this method ensures that all
>        of that data is there

This is problematic, for 2 reasons. First, v2 of the API uses all available HTTP methods: `GET`, `POST`, `PATCH`, `PUT`, and `DELETE`. So that means that none of those methods are getting the same treatment. Second, the treatment this method is performing may not be applicable to v2, and could even be causing problems.

Because of this, I would propose that the testing gets switched to use the [responses](https://github.com/getsentry/responses) library. In this way, the full HTTP request can be verified, from what URL is being called, to what parameters are used, to what headers and cookie are sent.

This does present a bit of a quandary, however. While I have v2 theoretically near completion in #11, including full test coverage... I fear that it may not actually work properly. Or, if it does, it may be by pure luck. On the other hand, I think that this change to the testing approach belongs in a full separate PR, as it will be quite a large change, and my current work is already reaching massive proportions.

So I think what I would like to propose is that #11 gets finalized and merged, then work can begin immediately on this change, prior to a new release going out.

Thoughts?

### PR DESCRIPTION
**Pull request by tarkatronic**
This fixes #12. I'm starting this PR out small as a draft, to give an idea of what it will look like, and make sure everybody is on board with the change.

This is to start using https://github.com/getsentry/responses instead of direct mocks for the actual API calls. The big advantage here is that we see what each actual full API call itself looks like, rather than just what the call to the internal methods looks like.

If an improper API call happens now, you see an error along the lines of either:
```
AssertionError: Expected call: post_request('foo', cookies=None, data=None, headers=None, params={'api_key': 'KEY', 'api_secret': 'SECRET', 'version': 1, 'foo': 'bar'})
Actual call: post_request('foo', cookies=None, data=None, headers=None, params={'api_key': 'KEY', 'api_secret': 'SECRET', 'foo': 'bar'})
```
or
```
requests.exceptions.ConnectionError: Connection refused by Responses: POST http://foo.com/users/ID/meetings?user_id=ID&topic=TOPIC&type=TYPE doesn't match Responses Mock
```

This should help a lot with diagnosing and preventing bugs like #21. In fact, you can see that I already discovered and fixed one bug thanks to this method; the `version` parameter was being passed along in the call to the API in v1. While this shouldn't be a breaking bug, it's certainly unintended.

### CODE REVIEW

**Comment by tarkatronic** [comment]
@prschmid @imreACTmd Let me know if this is a direction which interests you and I'll continue down this path. :) I think it adds some great value to the tests, and fully ensures the API calls are correct!

**Comment by prschmid** [comment]
@tarkatronic Yes, this looks like a great way to take the tests! Anything to make them more accurate based on what is actually happening is a good thing. Thanks for taking this on!

**Comment by tarkatronic** [comment]
@prschmid Just finished this up; ready to go when you are!

**Comment by tarkatronic** [comment]
@prschmid Any chance of a look at this? I think it would be helpful for the tests to be added in #31 😄

**Comment by prschmid** [comment]
@tarkatronic I've been dragging my feet on this because of the myriad of other commitments I've had over the past couple of months. Are you still up for making this change? A couple new things got merged in recently, so there might be some updates that have to be made on this PR. 

Thank you again for helping out on this!

**Comment by tarkatronic** [comment]
> @tarkatronic I've been dragging my feet on this because of the myriad of other commitments I've had over the past couple of months. Are you still up for making this change? A couple new things got merged in recently, so there might be some updates that have to be made on this PR.
> 
> Thank you again for helping out on this!

Sure thing, I'll be happy to get this updated! I've seen all the bug reports coming in and thinking this could help out, especially with people reporting exactly what they were sending to the API. These tests can ensure the code is doing precisely that with each call!

**Comment by tarkatronic** [comment]
I accidentally deleted this branch, so this PR is fried. I've got it rebased now; I'm just going to ensure I have all of the tests converted still, and then I will re-open! I think it will also be beneficial to wait for #77 to be merged before this gets marked as final.

**Pull request closed without merging**
