### PR TITLE
Add and list registrants for a meeting - fixes

### PR DESCRIPTION
**Pull request by ducpho**
Thanks to @thomjass for this functionality.

Just some small improvments on his PR (#87):
- fixed tests
- added test for updating meeting registrant status
- fix updateing meetings registrant status
- update readme
- clean up commit history

(Please let me know if I should open this PR on @thomjass repo instead.)

### CODE REVIEW

**Comment by cnuss** [comment]
@ducpho @thomjass thanks for the work on this!

@prschmid could we get #105 merged and released sometime soon?

**Comment by ducpho** [comment]
@cnuss In case you're pressed for time like me, I made [a pre-release](https://github.com/ducpho/zoomus/releases/tag/1.1.4-alpha.meeting-registrants4) and use it in production already 🤠.

**Comment by chirag200666** [comment]
+1 for the PR, would need it for my use case as well.

**Comment by prschmid** [comment]
Apologies for the delay on my end! It's been a very hectic couple of months. I'll get this reviewed in the next couple of days.

**Review by prschmid — APPROVED** [review]
Looks great. Thank you for your efforts, it's very much appreciated!

**Pull request merged**
