### PR TITLE
Add support for groups endpoint

### LINKED ISSUE #132: Add support for Groups & Group Membership
Zoom provides the ability to manage user permissions through groups. This is available in the [V2 API](https://marketplace.zoom.us/docs/api-reference/zoom-api/groups/). I've opened #131 to bring in this new component. I hope that's helpful!

### PR DESCRIPTION
**Pull request by dchess**
Fixes #132 
This PR includes a new component for the [groups endpoint](https://marketplace.zoom.us/docs/api-reference/zoom-api/groups/) and and group membership. Needed during new user creation if automation for group permissions is desired.

### CODE REVIEW

**Comment by prschmid** [comment]
@dchess Thanks for this PR! Looks like there is a conflict due to some formatting updates that were made when upgrading black to the latest version. Can I trouble you to pull the most recent `develop` and address the issues? Thank you!

**Comment by dchess** [comment]
@prschmid Take another look. I think that latest commit fixed the issue.

**Comment by prschmid** [comment]
Much appreciated! I'll get to this in the next couple of days so that we can get it merged in.

**Review by prschmid — APPROVED** [review]
LGTM! Thank you for all your efforts!

**Pull request merged**
